### ISSUE TITLE
Class 'PR\DHL\REST_API\Drivers\WP_API_Driver' not found in /plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-deutsche-post.php:117

### ISSUE THREAD

**Issue by dhana-listandsell** [shadimanna/dhl-logistic-services-for-woocommerce#137]
Unfortunately this error came. Can you check the errors?

WordPress version 6.0.2
Woocommerce version Version 6.9.1

Fatal error: Uncaught Error: Class 'PR\DHL\REST_API\Drivers\WP_API_Driver' not found in /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-deutsche-post.php:117 

Stack trace: 
#0 /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-deutsche-post.php(77): PR_DHL_API_Deutsche_Post->create_api_driver() 
#1 /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-factory.php(103): PR_DHL_API_Deutsche_Post->__construct('CH') 
#2 /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(474): PR_DHL_API_Factory::make_dhl('CH') 
#3 /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(273): PR_DHL_WC->get_dhl_factory() 
#4 /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(222): PR_DHL_WC->get_pr_dh in /www/htdocs/w0093876/synergo.winshop24.de/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-deutsche-post.php on line 117

screenshots:
1. https://prnt.sc/bE5qW6lAoxbJ
2. https://prnt.sc/2Z5T7cmJX80u

**Comment by Abdalsalaam** [comment]
Hi @dhana-listandsell  
Can you provide more details ? How can I re-create this issue ? did you update the plugin to the [latest version](https://wordpress.org/plugins/dhl-for-woocommerce/) ?

**Comment by dhana-listandsell** [comment]
The issue occurred when country is select other than germany in european countries in woocommerce settings. 
the issue so far is, it is breaking the whole website. Or it should atleast give alert that these countries are not to be selected

**Comment by sal4sup** [comment]
This was reported on an old version (WC 6.9 / 2022) and the API layer has since been substantially reworked. Please retest on the latest plugin version; if the fatal still occurs when a non-DE country is selected, reopen with the current version number and stack trace. Closing as stale.
