### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Abdalsalaam** [shadimanna/dhl-logistic-services-for-woocommerce#256]
```php
[22-Nov-2024 10:35:13 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /srv/data/web/vhosts/www.mysite.com/htdocs/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-wc-order-paket.php:805
Stack trace:
#0 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(275): PR_DHL_WC_Order_Paket->delete_label_args()
#1 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(357): PR_DHL_WC_Order->processing_delete_label()
#2 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-includes/class-wp-hook.php(324): PR_DHL_WC_Order->delete_label_ajax()
#3 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /srv/data/web/vhosts/www.mysite.com/htdocs/wp-admin/admin-ajax.php(192): do_action()
#6 {main}
  thrown in /srv/data/web/vhosts/www.mysite.com/htdocs/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-wc-order-paket.php on line 805
```

**Comment by sal4sup** [comment]
Resolved in v4. This fatal (`Cannot access offset of type string on string`) occurred when the `_pr_shipment_dhl_label_tracking` order meta was stored as a string and the delete-label flow indexed into it without a type guard. `get_dhl_label_tracking()` now guarantees an array (`return is_array( $label_tracking ) ? $label_tracking : array();`), so the offset access can no longer occur. Closing as fixed in the current release — please reopen if it still reproduces on the latest version.
